version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "12:00"
    timezone: Europe/Kiev
  open-pull-requests-limit: 99
  versioning-strategy: increase
